import Head from 'next/head'
import Navbar from '@/Components/Navbar'
import Card from '@/Components/Card'
import { HStack, SimpleGrid  } from '@Chakra-ui/react'
import SearchBar from '@/Components/SearchBar'

export default function Home() {
  return (
    <>
      <Head>
        <title>NGO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <SearchBar />
      <SimpleGrid minChildWidth='350px' spacingX='20px' spacingY='20px'>
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
        <Card />
      </SimpleGrid>  

    </>

  )
}
